### ISSUE TITLE
Helm 3 installation in Mac

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/solution-tutorials#100]
Helm 3 installation from this site is now working in Mac env:
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-tutorials

Helm command generates the following error:
“helm” cannot be opened because the developer cannot be verified.

**Comment by l2fprod** [comment]
@bkoohi 

in the instructions, there is:

> macOS Catalina may prompt you with a message saying the developer cannot be verified. To allow oc to be executed anyway, run `sudo xattr -r -d com.apple.quarantine /usr/local/bin/helm`.

this should solve the problem. Another option is to find the command in the Finder, then to right click and use Open. It will prompt to allow the command to run.

**Comment by bkoohi** [comment]
Thank you. Missed that note. It worked.

**Comment by bkoohi** [comment]
Thank you.
