### ISSUE TITLE
terraform

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/solution-tutorials#101]
Hi There 

Under terraform tool for provider installation, there is a hyperlink pointing to:
https://cloud.ibm.com/docs/terraform?topic=terraform-setup_cli#install_cli
This link is not working.

Correct link might be:
https://cloud.ibm.com/docs/ibm-cloud-provider-for-terraform?topic=ibm-cloud-provider-for-terraform-setup_cli#install-provider-v12

Thanks
Behzad

**Comment by l2fprod** [comment]
fixed. will show up in the next drop
