### ISSUE TITLE
Windows Bastion host recommendation

### ISSUE THREAD

**Issue by ibm-jawahar-vaiyapuri** [ibm-cloud-docs/solution-tutorials#103]
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-secure-management-bastion-server#vpc-secure-management-bastion-server

This document talks more on Linux Bastion host, requesting documentation link for Windows Bastion host.

Thanks.

**Comment by data-henrik** [comment]
The tutorial uses a Linux-based bastion host, correct. Everything is in a Virtual Private Cloud and the selected image for the virtual servers in the full scenario are Linux. For that tutorial it does not make sense to use Windows.

The same principles apply. What are you looking for specifically?

(I am closing this request, but you may continue to comment).

**Comment by ibm-jawahar-vaiyapuri** [comment]
@data-henrik We have use case on Windows Bastion Host to manage VPC with Windows Servers in IBM Cloud. Part of this we are looking for IBM Cloud's recommendation on Security, Hardening and logging of activities of Windows Bastion host.

**Comment by data-henrik** [comment]
I understand, but you are commenting on Solution Tutorials, not on documentation for VPC or virtual servers with Windows. There are the VPC principles which are discussed in the solution tutorial (not VPC documentation). Then, there is general administration of Windows machines. From the link you provided, the blog post also points to Microsoft tools and documentation.

In terms of VPC, the tutorial discusses security groups which apply to a virtual server instance (VSI), independent of its operating system.

**Comment by ibm-jawahar-vaiyapuri** [comment]
I understand that this is not VPC and or Windows VSI documentation, question is will there be any solution tutorial which will discuss on Windows Bastion host.

I assume that this is not planned as of now.

**Comment by data-henrik** [comment]
I suggest to open an issue against the VPC docs, similar to what you did here. https://github.com/ibm-cloud-docs/vpc/issues
