### ISSUE TITLE
Origin pool labels are backwards

### ISSUE THREAD

**Issue by bwoolf1** [ibm-cloud-docs/solution-tutorials#106]
Two section labels are backwards in [Resilient and secure multi-region Kubernetes clusters with IBM Cloud Internet Services](https://cloud.ibm.com/docs/cis?topic=solution-tutorials-multi-region-k8s-cis).

In [Resilient and secure multi-region Kubernetes clusters with IBM Cloud Internet Services](https://cloud.ibm.com/docs/cis?topic=solution-tutorials-multi-region-k8s-cis) > [Step 3: Configure multi-location load-balancing](https://cloud.ibm.com/docs/cis?topic=solution-tutorials-multi-region-k8s-cis#multi-region-k8s-cis-4) > [Define Origin Pools](https://cloud.ibm.com/docs/cis?topic=solution-tutorials-multi-region-k8s-cis#multi-region-k8s-cis-13):
- The section labeled [One pool for the cluster in London](https://cloud.ibm.com/docs/cis?topic=solution-tutorials-multi-region-k8s-cis#multi-region-k8s-cis-14) defines the `us-cluster` origin
- The section labeled [One pool for the cluster in Dallas](https://cloud.ibm.com/docs/cis?topic=solution-tutorials-multi-region-k8s-cis#multi-region-k8s-cis-15) defines the `uk-cluster` origin

**Comment by dprosper** [comment]
Thank you for catching this.  Updated and should be available at next documentation release update.
