### ISSUE TITLE
What is a Service Key and how to use it?

### ISSUE THREAD

**Issue by heyfrancisco** [ibm-cloud-docs/solution-tutorials#112]
Hello team, recently I was looking at this particular documentation and I got stuck trying to find what is a service key and where do I find it (since it's needed to finish this guide).

Would be good if you could add some more links/info explaining what is the service key and how do people find their service key. This service key needs to be added later to the .env file from MongoDB.

Many thanks.
Francisco Ramos do Ó

**Comment by heyfrancisco** [comment]
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-mean-stack

Step 1 - Point 4

**Comment by data-henrik** [comment]
Do you mean this section?
![image](https://github.com/ibm-cloud-docs/solution-tutorials/assets/8414748/c4efdbb1-f378-42f4-b0c4-3fd185d31648)

The command is used to create a service key. They are credentials for a service

**Comment by data-henrik** [comment]
I will close the issue. Please reopen if my answer did not help.
