### ISSUE TITLE
Serverless web application and API - binding-for-guestbook - JSON parameters incorrect

### ISSUE THREAD

**Issue by rnwolf** [ibm-cloud-docs/solution-tutorials#59]
Step 5 of the document for [serverless-api-webapp](https://github.com/ibm-cloud-docs/tutorials/blob/master/serverless-api-webapp.md) to test the binding-for-guestbook function says:

5. To test it, click on **Invoke with parameters** and enter the JSON below
   ```json
   {
     "name": "John Smith",
     "email": "john@smith.com",
     "comment": "this is my comment"
   }
   ```
This gives an error when invoking the function.

The JSON should be:
```
{
  "doc": {
    "comment": "this is my comment",
    "email": "john@smith.com",
    "name": "John Smith"
  }
}
```

**Comment by l2fprod** [comment]
@rnwolf 

to test the sequence 

```
{
  "name": "John Smith",
  "email": "john@smith.com",
  "comment": "this is my comment"
}
```

should be sufficient as the first action `prepare-entry-for-save` in the sequence will enclose the object into a `doc` for the cloudant `create-document` to work. 

https://github.com/ibm-cloud-docs/tutorials/blob/master/serverless-api-webapp.md#sequence-of-actions-to-save-the-guestbook-entry
