### ISSUE TITLE
Unable to create service key on Postgres as Administrator

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/solution-tutorials#61]
Tutorial:
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-site2site-vpn#deploy

In Postgres - step 2, I'm unable to create a service key while running the command:
```
ibmcloud resource service-key-create vpns2s-pg-key Administrator --instance-name vpns2s-pg
```

![image](https://user-images.githubusercontent.com/12241613/83635933-59066680-a5a5-11ea-976e-92641f17fe65.png)

Workaround:
I was able to workaround by creating a Service Credentials

![image](https://user-images.githubusercontent.com/12241613/83636418-3de82680-a5a6-11ea-96d4-6d426158603e.png)

**Comment by dprosper** [comment]
Thank you for reporting this, an update to the CLI removed that requirement for the role to be passed, we have updated the tutorial and the update should be published shortly.

```
ibmcloud resource service-key-create vpns2s-pg-key --instance-name vpns2s-pg
```
