### ISSUE TITLE
Issue with Guestbook application

### ISSUE THREAD

**Issue by kimlngo** [ibm-cloud-docs/solution-tutorials#62]
Hi,

I'm following the instructions in this document:
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-serverless-api-webapp

I successfully created all the back-end functions with sequences and tested using REST API calls, the sequences work as expected (retrieved entries in the guestbook as well as added new entries). However, upon integrating with the Front-end page hosted on github, I always hit the issue: 

"Access to XMLHttpRequest at 'https://abcxyz.us-east.apigw.appdomain.cloud/guestbook/entries' from origin 'https://kimlngo.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

I didn't see anything in the document mentioned about the fix for this issue. I googled a little bit but the temporary solution is not really comprehensive. 

Could you please look at this issue?

Overall, it is a really good tutorial to create back-end functions/sequences and integrate with front-end webpage.

Thanks & Regards
Kim Long

**Comment by l2fprod** [comment]
@kimlngo 

hi, in the API in Cloud Functions, please check whether CORS is enabled. By default it should be but it is worth checking

![image](https://user-images.githubusercontent.com/12746550/85302299-96f0ff00-b46e-11ea-9df4-b39113e82bb0.png)

**Comment by kimlngo** [comment]
@l2fprod 

Hi,

Thank you for your reply. I found the CORS setting was enabled and upon disabled, the github page works well as expected (both GET and PUT calls).

Just a further question regarding this: Would disabling this setting result in any security vulnerable?

Again, thanks for your help.

Best Regards
Kim Long

**Comment by l2fprod** [comment]
@kimlngo 

It should really be enabled. That's the only way the API running under appdomain.cloud can be embedded in another domain like github.io

Try a `curl -X OPTIONS -v https://abcxyz.us-east.apigw.appdomain.cloud/guestbook/entries`, you should see the CORS headers

```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
< Access-Control-Allow-Credentials: true
```

that is what your web browser is looking for.

**Comment by kimlngo** [comment]
@l2fprod 

Hi,

It's really weird that after disabling and re-enabling the setting, the application works well as expected. Now in the response headers, I do see what you have posted.

![image](https://user-images.githubusercontent.com/55027388/85308979-edb30480-b47f-11ea-9e4d-0e9afd9b69ce.png)

Thanks for your help.
