### ISSUE TITLE
Referenced page or info not found on IBM IOT platform dashboard

### ISSUE THREAD

**Issue by hmadduri** [ibm-cloud-docs/solution-tutorials#63]
In the tutorial here ( https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-gather-visualize-analyze-iot-data) there is reference to Historian Connector and the way to get there was to click on Help on IOT dashboard and then to APIs and then to Historian connector. 
None of those are available.  I searched IOT site for "Historian Connector" and nothing comes up.
Looks like the doc was updated in Feb 2020. Surprising it is out of date already.

**Comment by VidyasagarMSC** [comment]
@hmadduri I just created an IoT Platform service and could see the API under the help icon and also the Historian connector APIs
![2020-07-23 at 7 18 PM](https://user-images.githubusercontent.com/6552440/88294865-5b21b180-cd1a-11ea-9b29-d9dba70af99b.png)
![2020-07-23 at 7 19 PM](https://user-images.githubusercontent.com/6552440/88294888-5f4dcf00-cd1a-11ea-8b80-969bb7b2c6fc.png)

**Comment by hmadduri** [comment]
Ok, my mistake. thank you. You may close the ticket.   thanks    -Hari
    On Thursday, July 23, 2020, 08:56:52 AM CDT, Vidyasagar Machupalli <notifications@github.com> wrote:  
 
 


@hmadduri I just created an IoT Platform service and could see the API under the help icon and also the Historian connector APIs
