### ISSUE TITLE
Issues with starting node.js locally

### ISSUE THREAD

**Issue by blm849** [ibm-cloud-docs/solution-tutorials#64]
Hello, when I got to the section of this doc where I wanted to enter: node server.js

I received errors concerning bcrypt. I suspect the versions being used are out of date.

**Comment by l2fprod** [comment]
@blm849 

Hello, which specific tutorial are you going through?

**Comment by l2fprod** [comment]
Looks like it is the MEAN stack tutorial.

This commit https://github.com/IBM-Cloud/nodejs-MEAN-stack/commit/dc3d0a3331956113527a6184841bf9bd7d219738 should help.

Please reopen if you still encounter a problem
