### ISSUE TITLE
Missing outbound rule in Step 1: Create a bastion host

### ISSUE THREAD

**Issue by arvind-v** [ibm-cloud-docs/solution-tutorials#65]
Seems like the vpc-secure-bastion-sg created in Step 1 is missing an outbound rule to allow SSH to the instances that are part of the vpc-secure-maintenance-sg.

**Comment by data-henrik** [comment]
@arvind-v Are you referring to this tutorial? https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-secure-management-bastion-server

Step 1 indeed only has the inbound rules. In Step 2 both the inbound and outbound rules for vpc-secure-maintenance-sg are defined. Later, in step 2, the outbound rules for vpc-secure-bastion-sg are defined.

**Comment by arvind-v** [comment]
Yes, that was the tutorial I was referring to.  Thanks, I missed that instruction and also see why it in Step 2 since the vpc-secure-maintenance-sg needs to be first created.  I saw the title of the step ("Step 2: Configure a security group with maintenance access rules") and missed the part that it updates a rule within the bastion security group.  FYI - a nit: the numbering of steps within Step 2 is off.
