### ISSUE TITLE
Analyze and visualize open data with Apache Spark : Step 4: Transform data:  does not tell how to create the SQL Context

### ISSUE THREAD

**Issue by prsahoo** [ibm-cloud-docs/solution-tutorials#68]
Link to the tutorial:  https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-big-data-analytics-spark

Link to section 4 :  https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-big-data-analytics-spark#big-data-analytics-spark-4

Step 4: Transform data

```
sqlContext.registerDataFrameAsTable(df_pop, "PopTable")
df_pop = sqlContext.sql("SELECT `Country or Area` as Country, Year, Value as Population FROM PopTable")
df_pop.createOrReplaceTempView('population')
df_pop.printSchema()
```

Going by the command in the tutorial, we hit this error. 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-c7e8fc90f661> in <module>
----> 1 sqlContext.registerDataFrameAsTable(df_pop, "PopTable")
      2 df_pop = sqlContext.sql("SELECT `Country or Area` as Country, Year, Value as Population FROM PopTable")
      3 df_pop.createOrReplaceTempView('population')
      4 df_pop.printSchema()

NameError: name 'sqlContext' is not defined
```

**Comment by data-henrik** [comment]
@prsahoo Could you share more about your Spark and Notebook environment? It seems that the Spark session is not fully initialized or something has changed.

**Comment by data-henrik** [comment]
Watson Studio changed significantly in recent months and the tutorial is no longer in sync. We are going to retire the tutorial. Please see this notebook documentation for working examples that use a similar setup: https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/notebooks-parent.html?context=cpdaas
