### ISSUE TITLE
Step to create Watson Studio is now incorrect. Watson Studio is no longer a CF based service

### ISSUE THREAD

**Issue by naterry** [ibm-cloud-docs/solution-tutorials#69]
Please update the instruction with the correct instructions for create a resource based instance of Watson Studio,

e.g.

Current instuction:
![image](https://user-images.githubusercontent.com/49072806/93227812-b1383180-f76c-11ea-9361-9a6e80183d5a.png)

Should be:

ibmcloud resource service-instance-create <service instance name> data-science-experience free-v1 <region> -g <resource group>

**Comment by data-henrik** [comment]
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-smart-data-lake has been updated, another change is in the pipeline. Thank you for reaching out to us.
