### ISSUE TITLE
Issue in Step 4.5

### ISSUE THREAD

**Issue by plplatorre** [ibm-cloud-docs/solution-tutorials#70]
Hi!

I'm trying to follow the tutorial but in the 4th step, in the 5th sub-step I'm finding this issue:

```
(base) pedroluis@pedroluiss-mbp wikicompetitive-openshiftapp % oc status

In project wikicompetitive-openshiftapp on server https://c100-e.eu-de.containers.cloud.ibm.com:30884

dc/wikicompetitive-openshiftapp deploys istag/wikicompetitive-openshiftapp:latest 
  deployment #1 waiting on image or update

bc/wikicompetitive-openshiftapp docker builds https://gitlab+deploy-token-1022:oYxzbsEyHe_ZxbX_jhwy@eu-de.git.cloud.ibm.com/pedro.luis.perez/wikicompetitive-openshiftapp.git on istag/ubi8:latest
  -> de.icr.io/wikinamespace/wikicompetitive-openshiftapp:latest
  build #1 succeeded 9 seconds ago - 7a80da9: Update openshift.yaml (Pedro Luis Pérez <pedro.luis.perez@ibm.com>) (can't push to image)


1 warning, 2 infos identified, use 'oc status --suggest' to see details.
(base) pedroluis@pedroluiss-mbp wikicompetitive-openshiftapp % 
```

No other issue has risen before this point
I'm using OpenShift 4.5. on IBM Cloud and carrying all the process out in my Mac Os Terminal

Could you provide any help?
Thanks!

**Comment by VidyasagarMSC** [comment]
Had a couple of WebEx calls with Pedro to resolve this issue. The issue was with the YAML file not generating as expected (missing imagestreams and service components). Have to patch manually to make it work in eu-de.

**Comment by plplatorre** [comment]
Thanks to Vidyasagar the issue is now solved!
He has detected where the error comes from and also helped me in solving it manually
Thanks!
