### ISSUE TITLE
Wrong code in worldcities.py in https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-sql-database

### ISSUE THREAD

**Issue by deidrap** [ibm-cloud-docs/solution-tutorials#71]
When following the instructions on this page I got an error during cf push: 
 2020-11-11T13:35:50.56-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2020-11-11T13:35:50.56-0500 [APP/PROC/WEB/0] ERR   File "worldcities.py", line 19, in <module>
   2020-11-11T13:35:50.57-0500 [APP/PROC/WEB/0] ERR     db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
   2020-11-11T13:35:50.57-0500 [APP/PROC/WEB/0] ERR KeyError: 'dashDB'

This needs to be fixed in worldcities.py:
# get service information if on IBM Cloud Platform
if 'VCAP_SERVICES' in os.environ:
    db2info = json.loads(os.environ['VCAP_SERVICES'])['**dashDB**'][0]
    db2cred = db2info["credentials"]
    appenv = json.loads(os.environ['VCAP_APPLICATION'])

Should be changed to 
# get service information if on IBM Cloud Platform
if 'VCAP_SERVICES' in os.environ:
    db2info = json.loads(os.environ['VCAP_SERVICES'])['**dashDB For Transactions**'][0]
    db2cred = db2info["credentials"]
    appenv = json.loads(os.environ['VCAP_APPLICATION'])

**Comment by data-henrik** [comment]
Hello @deidrap, have you provisioned a Db2 Warehouse on Cloud as instructed in the tutorial? See https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-sql-database

Db2 on Cloud uses the service name "dashDB for Transactions", but Db2 Warehouse on Cloud is named "dashDB". Thus, the code should be correct.

**Comment by data-henrik** [comment]
closing it
