### ISSUE TITLE
The link to the Authorizatoin page is wrong

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/solution-tutorials#75]
Hi
in the section : https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-cloud-e2e-security#cloud-e2e-security-8
you have a link to the authorization page, but the link is wrong, I guess the correct link will be : https://cloud.ibm.com/iam/authorizations

**Comment by l2fprod** [comment]
will fixed in next drop, thank you!
