### ISSUE TITLE
"Gather, visualize, and analyze IoT data" is broken: pixiedust issue

### ISSUE THREAD

**Issue by ahnugent** [ibm-cloud-docs/solution-tutorials#76]
I can't get the Jupyter notebook to execute, owing to an exception from pixiedust. The line `pixiedust.installPackage("org.apache.bahir:spark-sql-cloudant_2.11:0")`
throws `AttributeError: module 'pixiedust' has no attribute 'installPackage'`

I've tried installing pixiedust and pixiedust_node, using pip and pip3. (I'm using the default Python 3.7 kernel).

**Comment by data-henrik** [comment]
Is pixiedust installed? We are updating the tutorials to account for pixiedust no longer being preinstalled. See here for the command to install it (in another tutorial): https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-smart-data-lake#smart-data-lake-5

`!pip install --user pixiedust`

**Comment by ahnugent** [comment]
Thanks for the reply. 
As in my original post, I installed pixiedust with pip and pip3 -- neither worked. I'm assuming the 'installPackage' class has moved to a sub namespace without being documented.

Anyway, the Node-RED part of the tutorial spontaneously broke, too -- so I think I have to write off that 3 hours as yet another IBM tutorial that doesn't work and move on to other things.

**Comment by data-henrik** [comment]
Hello Allen,
you might have noticed that re removed that tutorial due to many problems from service changes. Thank you for the feedback

**Comment by ahnugent** [comment]
Thanks, Henrik.

That's a shame, but I certainly understand.

Cheers,
Allen
