### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by carcaveman** [ibm-cloud-docs/solution-tutorials#77]
'import ibmcloudsql' returns an error of package not found

**Comment by data-henrik** [comment]
What tutorial are you referring to? Have you installed the package?

**Comment by carcaveman** [comment]
It's the exercise 'Build a data lake using object storage'. In step 4, sub
sep 2, they have you issue a command 'import ibmcloudsql', but when you do,
python returns an error indicating no such package is present.

Thanks, David Harper

By the way, I am IBM employee, but I couldn't log into regular GitHub with
my employee ID.

**Comment by data-henrik** [comment]
Hi David,

could you try executing this in a line before the import?

`!pip install --user ibmcloudsql`

Sometimes the environments change. It should be preinstalled.

**Comment by data-henrik** [comment]
I have added enhanced instructions to the tutorial.

   ```python
    !pip install --user --upgrade pixiedust
    !pip install --user --upgrade ibmcloudsql
    import ibmcloudsql
    from pixiedust.display import *
    ```

This is the updated step

**Comment by carcaveman** [comment]
Thanks, bit it doesn't show up on the website. Does it take time to get
published to the website?

David
