### ISSUE TITLE
Broken link in documentation for Updating the DNS resolver for your VSI

### ISSUE THREAD

**Issue by tking156** [ibm-cloud-docs/solution-tutorials#80]
On this page https://cloud.ibm.com/docs/dns-svcs?topic=solution-tutorials-vpc-tg-dns-iam
The link in step 5 section 2 "Updating the DNS resolver for your VSI " is bad an leads to page not available.
https://cloud.ibm.com/docs/dns-svcs?topic=dns-svcs-updating-dns-resolver

**Comment by l2fprod** [comment]
thank you. it will be fixed in our next push!
