### ISSUE TITLE
ipsec status reports no connections and no IKE config found

### ISSUE THREAD

**Issue by pamandrejko** [ibm-cloud-docs/solution-tutorials#83]
Tutorial: [Use a VPC/VPN gateway for secure and private on-premises access to cloud resources](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-site2site-vpn
)
In the step where we [Create the on-premises Virtual Private Network gateway](https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-site2site-vpn#vpc-site2site-vpn-10)

the ipsec status command reports no connections:
ipsec status
Security Associations (0 up, 0 connecting):
  none

HIDING ACTUAL IP's in the output below:

ipsec statusall
Status of IKE charon daemon (strongSwan 5.6.2, Linux 4.15.0-118-generic, x86_64):
  uptime: 10 minutes, since May 04 15:06:33 2021
  malloc: sbrk 1622016, mmap 0, used 617232, free 1004784
  worker threads: 11 of 16 idle, 5/0/0/0 working, job queue: 0/0/0/0, scheduled: 0
  loaded plugins: charon aesni aes rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac gcm attr kernel-netlink resolve socket-default connmark stroke updown eap-mschapv2 xauth-generic counters
Listening IP addresses:
  xx.xx.xx.194
  yy.yy.y.196
Connections:
tutorial-site2site-onprem-to-cloud:  %any...yy.yy.yy.36  IKEv1, dpddelay=30s
tutorial-site2site-onprem-to-cloud:   local:  [yy.yy.yy.196] uses pre-shared key authentication
tutorial-site2site-onprem-to-cloud:   remote: [yy.yy.yy.36] uses pre-shared key authentication
tutorial-site2site-onprem-to-cloud:   child:  zz.zz.zz.196/26 === zz.zz.zz.0/24 TUNNEL, dpdaction=restart
Security Associations (0 up, 0 connecting):
  none

I can provide the ipsec.conf file offline if needed.

Could it be that we are using the latest version of strongSwan which is not compatible with the ipsec.conf file provided in this tutorial?

journalctl --system -u strongswan
...
May 04 14:02:01 vpns2s-onprem-vsi charon[55730]: 06[IKE] no IKE config found for yy.yy.yy.196...yy.yy.yy.36, sending NO_PROPOSAL_CHOSEN
...

We tried adding `keyexchange=ikev1` to the ipsec.conf file but that did not change anything.

**Comment by powellquiring** [comment]
What version of strongSwan are you using?
Are you using the simulated on-premises environment on classic as described in the tutorial?

**Comment by pamandrejko** [comment]
It looks like strongSwan 5.6.2.
Yes we used the scripts from the tutorial to set up the simulated on-prem enviroment.

**Comment by powellquiring** [comment]
It is going to be difficult for me to replicate your environment.  Instead, can you try again building everything using the scripts.  Hopefully it will work.  Then you can then adjust it to meet your requirements and see if you can find the issue.

**Comment by powellquiring** [comment]
The cloud VPN  configuration had a typo  in the preshared key.

![image](https://user-images.githubusercontent.com/6932057/117190956-e1ccea00-ad94-11eb-9574-62b7edfa0dfb.png)
