### ISSUE TITLE
Incorrect title for resource

### ISSUE THREAD

**Issue by ktmn110** [ibm-cloud-docs/solution-tutorials#84]
In the IBM Cloud® Resource List open the overview of your services. Locate the instance of the **Watson Assistant** service created in the previous section. Click on its entry and then the service alias to open the service details.

Now shows up as **eventConversation** in the resource list.

**Comment by data-henrik** [comment]
Hello @ktmn110, I am looking at this tutorial: https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-slack-chatbot-database-watson

It seems you are referring to this section:
![image](https://user-images.githubusercontent.com/8414748/120994933-4230bc00-c785-11eb-859b-ebc2e18ca3cf.png)

Is this correct? 

The instance of Watson Assistant is named **eventConversation** and it should show up as such in the resource list. What do you see? What is the incorrect title?

**Comment by data-henrik** [comment]
Closing it for now. Please reopen if it is still unclear.
