### ISSUE TITLE
Securely access remote instances with a bastion host

### ISSUE THREAD

**Issue by luisfalcao** [ibm-cloud-docs/solution-tutorials#86]
An outbound rule is missing in step: Create and configure bastion security group.
To ssh -J <bastion> works, I had to create an outbound rule for 0.0.0.0/0 to any.

**Comment by data-henrik** [comment]
Isn't that added in Step 2.4? https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-secure-management-bastion-server#vpc-secure-management-bastion-server-maintenance-security-group

**Comment by data-henrik** [comment]
Let me know if that fixed it for you. I am closing this issue for now.
