### ISSUE TITLE
Receive an error after running Step 4, sub step 3

### ISSUE THREAD

**Issue by snyderdb** [ibm-cloud-docs/solution-tutorials#87]
When I run Step 4, sub step 3, I receive the following error:

ave@dave:~/kubernetes-node-app$ kubectl apply -f ingress-ibmdomain.yaml
The Ingress "ingress-for-ibmdomain-http-and-https" is invalid: 
* spec.rules[0].host: Invalid value: "dbskubenodeapp.": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* spec.tls[0].hosts[0]: Invalid value: "dbskubenodeapp.": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

Can someone provide any guidance/suggestions for resolving this error.

I have followed the steps carefully and do not feel I have made any errors up to this point.

**Comment by dprosper** [comment]
@snyderdb Can you provide a link to the tutorial you are following? I think we may need to redirect this inquiry to another repository...

**Comment by snyderdb** [comment]
hello Dimitri -
Its this tutorial:  https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-scalable-webapp-kubernetes
    On Tuesday, September 7, 2021, 07:49:21 AM EDT, Dimitri Prosper ***@***.***> wrote:  
 
 


@snyderdb Can you provide a link to the tutorial you are following? I think we may need to redirect this inquiry to another repository...

**Comment by dprosper** [comment]
> hello Dimitri - Its this tutorial:  https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-scalable-webapp-kubernetes On Tuesday, September 7, 2021, 07:49:21 AM EDT, Dimitri Prosper ***@***.***> wrote: @snyderdb Can you provide a link to the tutorial you are following? I think we may need to redirect this inquiry to another repository... — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you,  **I was searching the wrong repo ;-)** . I will take a look.

**Comment by dprosper** [comment]
@snyderdb The tutorial has a rendering issue and a step is not very visible, the section in the red box is meant to be a step, but it somehow ended up in the result box from the previous command

<img width="1012" alt="Screen Shot 2021-09-07 at 9 30 53 AM" src="https://user-images.githubusercontent.com/11874942/132353883-63716cce-05b6-4011-8ee9-c96f6c068098.png">

I will make the update and that should be available in a couple of hours, in the meantime you can run the two export commands as described above and replace with your ingress results.  once done re-run the shell script and then the kubectl apply.  

Thank you for reporting this problem

**Comment by dprosper** [comment]
updated the doc and published.
