### ISSUE TITLE
Upon Successful Install of OpenShift, the OpenShift Console Does Not Open

### ISSUE THREAD

**Issue by snyderdb** [ibm-cloud-docs/solution-tutorials#89]
After successfully installing OpenShift, and when attempt to open the OpenShift Console from within the IBM Cloud Console, the OpenShift console does not open.

**Comment by dprosper** [comment]
@snyderdb Do you think the issue is with the tutorial or your OpenShift cluster?  If tutorial can you link the tutorial you are going through.  If your cluster, your best bet is to open a Support Incident here: https://cloud.ibm.com/unifiedsupport/supportcenter

**Comment by snyderdb** [comment]
Thanks Dimitri -
I did open a ticket with support.  Thank you!
Certainly appreciate you following up!

    On Tuesday, September 14, 2021, 01:14:13 PM UTC, Dimitri Prosper ***@***.***> wrote:  
 
 


@snyderdb Do you think the issue is with the tutorial or your OpenShift cluster? If tutorial can you link the tutorial you are going through. If your cluster, your best bet is to open a Support Incident here: https://cloud.ibm.com/unifiedsupport/supportcenter
