### ISSUE TITLE
Need to add the command installing "tg" plugin of "ibmcloud" CLI

### ISSUE THREAD

**Issue by kyunghoryu** [ibm-cloud-docs/solution-tutorials#90]
At step 6: Create Transit Gateway, the command "ibmcloud tg gateways" mentioned at '5, print the transit gateway' would fail if the "tg" plugin is not installed.

$ ibmcloud tg gateways

FAILED

'tg' is not a registered command. See 'ibmcloud help'.

Since the output addresses no clear reason of the failure, the following lines should be added.

 
If the command failed, please install the "tg" plugin by running the command below

$ ibmcloud plugin install tg

**Comment by powellquiring** [comment]
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-vpc-tg-dns-iam

**Comment by VidyasagarMSC** [comment]
@kyunghoryu The updates are now live. Closing this issue.
