### ISSUE TITLE
Serverless web application and API - cos public endpoint cloudy

### ISSUE THREAD

**Issue by essie-chiang** [ibm-cloud-docs/solution-tutorials#96]
Page:
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-serverless-api-webapp#serverless-api-webapp
Step:
Navigate to the Configuration tab for the bucket and scroll down to the Static website hosting endpoints section to copy the Public endpoint into a browser tab.

public
Primary endpoint
Use public endpoints to point applications or services that are hosted outside of the IBM cloud or for Cloud Foundry applications hosted in the IBM cloud.

https://cloud.ibm.com/maintenance/undefined

**Comment by l2fprod** [comment]
@essie-chiang 

thank you for reporting.

looks like an issue in the coding of the link in the page. If you copy the text that you see in the page it works but indeed clicking the link does not work. I'll pass on the issue to the product team
