### ISSUE TITLE
Got stuck at Step 2: Load the skill / workspace

### ISSUE THREAD

**Issue by R3dje** [ibm-cloud-docs/solution-tutorials#97]
At "Step 2: Load the skill / workspace" the descriptions describes to Launch Watson Assistant.
This is going ok, but the steps after are not in Watson Assistant any more. 
I can't find anything with "Skills" or choose a JSON file. 
I think everything in Step 2-2 to 5 is changed and the documentation should be updated.

**Comment by data-henrik** [comment]
Are you using the Classic version as instructed here? https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-slack-chatbot-database-watson#slack-chatbot-database-watson-3

**Comment by data-henrik** [comment]
![image](https://user-images.githubusercontent.com/8414748/149497613-5cad669d-872e-4b4f-b23a-0885d76f786b.png)
I created a new lite instance of Watson Assistant 2 minutes ago and, after switching to the classic experience, could upload a skill.
