### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by SamHobbsOrg** [ibm-cloud-docs/solution-tutorials#98]
In the _Accelerate delivery of static files using a CDN_ tutorial I assume that the _bucket API endpoint_ is the same as the bucket public endpoint. The name _API endpoint_ is not used in the resource creation page; is it an old term? I think it should be changed in the tutorial, either clarification added or the name _API endpoint_ should be changed to _public endpoint_.

**Comment by l2fprod** [comment]
fixed. will be visible on our next update.
